### ISSUE TITLE
Missing did:stack

### ISSUE THREAD

**Issue by jcnelson** [w3c-ccg/did-method-registry#11]
The Blockstack DID format is not listed in the registry, but it exists and has been supported in production for some time.

**Comment by msporny** [comment]
If you could submit a PR that points to a spec, we can include it. Or if you can just point to a spec, one of us will add it to the registry for you.

**Comment by jcnelson** [comment]
Is there a template you would prefer us to conform to?

**Comment by msporny** [comment]
Something like this if you can swing it: https://w3c-ccg.github.io/didm-veres-one/ or this: https://sovrin-foundation.github.io/sovrin/spec/did-method-spec-template.html

If not, just a Markdown file would be enough for us to put you in the registry. 

Unfortunately, it's a bit free form right now, but at least mention how one would create, read, update, and delete/revoke a DID in your ledger.

**Comment by jcnelson** [comment]
Here you go: https://github.com/blockstack/blockstack-core/blob/master/docs/blockstack-did-spec.md

**Comment by ChristopherA** [comment]
Glad to see this posted! We should get you to present at an upcoming W3C
Credentials CG meeting soon.

— Christopher Allen [via iPhone]

**Comment by msporny** [comment]
Done in https://github.com/w3c-ccg/did-method-registry/commit/e2529ee27cea05a6522087976a57048d229365fc. Thanks @jcnelson!
