### ISSUE TITLE
Dominode is missing a method spec link

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/did-method-registry#29]
The commit lists @ricjcosme as the author

**Comment by peacekeeper** [comment]
I just sent them an e-mail to point them to this issue, but I'm not sure what their status is.

**Comment by kimdhamilton** [comment]
Moved to [DID spec registry](https://github.com/w3c/did-spec-registries). Tracked with issue: https://github.com/w3c/did-spec-registries/issues/105
