### ISSUE TITLE
uPort is missing a method spec link

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/did-method-registry#31]
It was in the original commit, so I don't have an author

**Comment by awoie** [comment]
Thanks for pointing out that the spec was missing.

did:uport is deprecated and can be removed. We encourage people to use our new did:ethr method which is already registered.

**Comment by kimdhamilton** [comment]
We just need to update status; this depends on #36

**Comment by OR13** [comment]
@awoie can you take a stab at resolving this issue?

**Comment by kimdhamilton** [comment]
Moved to [DID spec registry](https://github.com/w3c/did-spec-registries). Tracked with issue: https://github.com/w3c/did-spec-registries/issues/105
