### ISSUE TITLE
Add note to did method registry process about versioning method specs in a way that bubbles up to the registry

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/did-method-registry#36]
From CCG call on 2 April 2019: https://w3c-ccg.github.io/meetings/2019-04-02/#action-1

"add note to did method registry process about versioning method specs in a way that bubbles up to the registry"

Relevant context:
Kim: Uport, might be useful to mark this one as deprecated, since people may be working with it
Joe Andrieu: +1 To retaining uport as "deprecated"
Jonathan Holt: Version control issues; machine readable
Joe Andrieu: +1 To add version to registry
... For version control, implement a better syntax around changes and whether it has been deprecated
Manu Sporny: Specification should have version in the title
... JSON-LD can support the other request, this is a respec feature
... This requires work by the people writing the specifications, not everyone does that
Drummond Reed: +1 To adding that note to the registry instructions. ✪

**Comment by OR13** [comment]
@awoie ^ can you assign someone to this?

**Comment by kimdhamilton** [comment]
Moved to [DID spec registry](https://github.com/w3c/did-spec-registries). Tracked with issue: https://github.com/w3c/did-spec-registries/issues/105
