### ISSUE TITLE
Move the DID Method Registry into the DID Core Registries

### ISSUE THREAD

**Issue by rhiaro** [w3c-ccg/did-method-registry#82]
The [DID Core Registries](https://github.com/w3c/did-core-registries) are the place for coordinating interop around extension properties and parameters. In the interests of having one place to look for stuff, the DID Method Registry should be part of that as well.

The CCG will need to pass a formal resolution to do this, I think.

@ChristopherA @kimdhamilton @jandrieu @burnburn @brentzundel @msporny @OR13

**Comment by OR13** [comment]
let me know when I can open a PR against that repo to move it.... I'm not planning on migrating git history... so we should make sure to merge any open PRs / close them and mark this repo as Archived as  soon as this is decided.

**Comment by jandrieu** [comment]
I sent an email to the DID WG chairs and the current editors. We'll have to figure out the process for winding up the CCG's work item, but we first should start with a formal request/adoption by the WG and confirm the current editors are on board with that.

**Comment by kimdhamilton** [comment]
this is complete (https://w3c.github.io/did-spec-registries/#did-methods)
