### ISSUE TITLE
Define Contribution Requirements

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/did-method-registry#85]
Is "Privacy Considerations" required?

See: https://github.com/w3c-ccg/did-method-registry/pull/84

https://w3c.github.io/did-core/#privacy-considerations is non-normative.

**Comment by msporny** [comment]
It's not just Privacy Considerations, but Security and Privacy Considerations, which is a standard requirement for all W3C specs that have those sorts of impacts -- Accessibility and Internationalization are two other semi-optional parts.

Yes, we're not clear on this in the registration process and need to be more clear. The requirement has evolved after we saw a few DID Methods that had blatant privacy and security holes, and it was clear that the method implementers weren't thinking at all about either aspect of their DID Method.

The DID spec, though, is crystal clear on these sections being a requirement... and conforming to the DID spec is a requirement (see the process) for eventually being listed as a PRODUCTION method in the registry:

https://w3c.github.io/did-core/#security-requirements
https://w3c.github.io/did-core/#privacy-requirements

All that said, we should be a bit more clear as there are many people that have tried to register DID Methods w/o realizing all of the sections they need to define.

**Comment by kimdhamilton** [comment]
Moved to [DID spec registry](https://github.com/w3c/did-spec-registries). Tracked with issue: https://github.com/w3c/did-spec-registries/issues/105
