### ISSUE TITLE
ARCHIVE IMMEDIATLY

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/did-method-registry#98]
This repo has moved here: https://w3c.github.io/did-spec-registries/#did-methods

We need to archive this repo ASAP and direct people to move issues / PRs there... and not open PRs here.

@kimdhamilton @ChristopherA @jandrieu @msporny 

Can I archive this repo?

**Comment by wyc** [comment]
By the powers vested in me by [this announcement](https://lists.w3.org/Archives/Public/public-credentials/2020Jun/0203.html), and the lack of sustained objections, I will now oblige this request.
